[package]
name = "generate"
version = "0.1.0"
authors = ["Ulrich Berthold <u@sansculotte.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.2"
rand = "0.6.5"
